### ISSUE TITLE
ModuleNotFoundError: No module named 'email_reply_parser'

### ISSUE THREAD

**Issue by Christovis** [INDElab/conversationkg#5] opened 2021-02-19 19:57 UTC
After installing as described in the README, trying to run the tests failes as the `email_reply_parser` module can't be found.

Error message:
```
File "/conversationkg/tests/tests.py", line 3, in <module>
    from conversationkg import example_mailinglists, load_example_data_as_raw_JSON
  File ".local/lib/python3.9/site-packages/conversationkg/__init__.py", line 1, in <module>
    from .sample_data.load import load_data_raw as load_example_data_as_raw_JSON
  File ".local/lib/python3.9/site-packages/conversationkg/sample_data/load.py", line 4, in <module>
    from ..conversations import EmailCorpus
  File ".local/lib/python3.9/site-packages/conversationkg/conversations/__init__.py", line 1, in <module>
    from .corpus import EmailCorpusCollection, EmailCorpus, Conversation, group_by_subject_line, group_by_id
  File ".local/lib/python3.9/site-packages/conversationkg/conversations/corpus.py", line 12, in <module>
    from .emails import Email
  File ".local/lib/python3.9/site-packages/conversationkg/conversations/emails.py", line 8, in <module>
    from email_reply_parser import EmailReplyParser
ModuleNotFoundError: No module named 'email_reply_parser'
```

**Comment by valevo** [comment] 2021-02-20 12:57
Hi,

thanks for your message and nice that you're working with the package.
The package is still being developed so some features might break or be broken, sorry for that. Within the month, however, development is being wrapped up, so after everything should work fine.

Regarding the error you got, I can't reproduce it unfortunately. Are you sure that the `email_reply_parser` package is installed on your system? It is an external dependency, so requires to be installed separately (make sure that all packages listed in [requirements.txt](https://github.com/INDElab/conversationkg/blob/master/requirements.txt) are installed before using `conversationkg`). That's the most likely source of the error you received.

Please let me know if this solves your issue.

**Comment by Christovis** [comment] 2021-02-20 15:48
Oh I see! I have indeed forgotten to install `email_reply_parser`!
Sorry I thought `python -m pip install .` would do everything that needs to be done to get the package running.
Maybe it would be convenient to place a `'install_requires'` argument within `setuptools.setup()` where the requirements with version conditions are listed (most common way now-a-days if conda isn't used).

P.S.: btw. I am the person working with Niels on BigBang :wink:

**Comment by pgroth** [comment] 2021-03-05 16:10
I'll leave this open. The requirements.txt file isn't properly installing. Also agree with @Christovis that we need to be able to install requirements before hand..

**Comment by valevo** [comment] 2021-03-06 11:08
Okay, I see your points. Thanks for the tip, @Christovis, I did exactly that and added the contents of requirements.txt as the  `install_requires` argument. This should fix the unmet dependency issue (tested but obviously I already have all dependencies installed on my computer), if doesn't please do let me know. I'll close this issue now...

**Closed by valevo** 2021-03-06 11:08 UTC
